### ISSUE TITLE
Question for masked_loss

### ISSUE THREAD

**Issue by planemanner** [NExT-ChatV/NExT-Chat#14]
Hi, thank you for your implementation.

While I'm viewing your code lines, a question arises about the 'masked loss.'

Why do you mask out the last part of each loss using this function?

https://github.com/NExT-ChatV/NExT-Chat/blob/1e6c20f7e88feea44985e6dacbddc3c4d5701e3e/mllm/models/nextchat/nextchat_base.py#L360

**Comment by waxnkw** [comment]
Thanks for your interest! There is a mock sample appended as the last sample in each batch. However, the mock sample should not be used in calculating the loss. Thus, we use a masked loss to set the weight of the mock sample as zero.

Why we need a mock sample?
In the training, there exists some batches without box input/output. The lack of object input/output will lead to no grads for the box encoder and decoder, which will cause a runtime error.

**Comment by planemanner** [comment]
> Thanks for your interest! There is a mock sample appended as the last sample in each batch. However, the mock sample should not be used in calculating the loss. Thus, we use a masked loss to set the weight of the mock sample as zero.
> 
> Why we need a mock sample? In the training, there exists some batches without box input/output. The lack of object input/output will lead to no grads for the box encoder and decoder, which will cause a runtime error.

Thank you for quick response and clear explanation !
