### ISSUE TITLE
Missing requrement and asset!

### ISSUE THREAD

**Issue by yhyu13** [NExT-ChatV/NExT-Chat#2]
HI

I found these packages still missing when deploying locally, simply pip install these would make local demo work
```
torch
torchaudio
torchvision
pycocotools
pycocoevalcap
sentencepiece
```

And it seems the dog.png image has been missing, is it deleted or is it not uploaded? I have to comment related code out other demo wouldn't pass

![next-chat5](https://github.com/NExT-ChatV/NExT-Chat/assets/19365678/2c04306f-f6d9-4eee-8851-4bbc49e72870)

**Comment by waxnkw** [comment]
Thanks for pointing out! I upload dog.png.
